### ISSUE TITLE
Groundskeeper Too Verbose

### ISSUE THREAD

**Issue by bobjackman** [couto/grunt-groundskeeper#3]
Would it be possible to change the majority of the `grunt.log` messages to use `grunt.verbose` instead? I'm finding that most packages have some type of option to control their output, and also that Groundskeeper (which is otherwise awesome, btw), is flooding my screen with output that, 99% of the time I just don't care about.

Most of the time everything works as expected and I don't need to see this output, and in the rare case that something goes wrong, I can always use `--verbose` to see exactly what Groundskeeper is doing.

A similar request (and solution) was discussed (and implemented) in grunt-contrib-copy: https://github.com/gruntjs/grunt-contrib-copy/pull/62

**Comment by couto** [comment]
No problem actually.
Just wondering, would you prefer to just tell you which files it cleaned, or just the number of files?

**Comment by bobjackman** [comment]
My personal preference would be for it to show something like either of these (or similar):
1. `Cleaned x Files in y Directories`
2. `Scanned Files: x, Cleaned Files: y`
3. `Scanned x Files, removed y Occurrences` -- where occurrences would be 1 per pragma block and 1 per namespace reference.

This is just my personal preference, though, and some other solution may or may not prove to be better for the masses.

Thanks!

**Comment by couto** [comment]
It's currently impossible to tell how many console/pragmas were removed (for now at least) due the way groundskeeper is done.

It will notify about how many files were read and how many were cleaned. 
Feel free to suggest any changes and please report any bug you encounter. 

It's really hard to find edge cases to test groundskeeper so any input is always welcome ;)

P.S.: I'm kinda busy at the moment, so this fix wasn't deeply tested. I'm sorry for that, if you find something odd, please report it and my apologies in advance.

**Comment by bobjackman** [comment]
Wow! Super fast response! Thank you! Tested for my application and works great. +1 for awesome support :+1:
