### ISSUE TITLE
how to remove all console but console.error

### ISSUE THREAD

**Issue by atian25** [couto/grunt-groundskeeper#5]

**Comment by couto** [comment]
I never really needed that option, so I guess it's not possible in an easy way.

The only way I can imagine that would work, would be to declare every method present in `console` but `console.error`, in the namespace array.

I wouldn't mind a pull request with RegEx support for namespaces. ;)

**Comment by atian25** [comment]
I'm writing a hybrid app, need to collect `warn/error` to server by android's `onConsoleMessage`.

workround: 

```
        options: {
          console: true,
          namespace: [
            "console.log",
            //"console.info",
            //"console.warn",
            //"console.error",
            "console.assert",
            "console.count",
            "console.clear",
            "console.group",
            "console.groupEnd",
            "console.groupCollapsed",
            "console.trace",
            "console.debug",
            "console.dir",
            "console.dirxml",
            "console.profile",
            "console.profileEnd",
            "console.time",
            "console.timeEnd",
            "console.timeStamp",
            "console.table",
            "console.exception"
          ]
        }
```

a pull request will be soon.

**Comment by couto** [comment]
You may want to make the pull request to [groundskeeper](https://github.com/Couto/groundskeeper) instead of this package, since this is just the grunt's wrapper.

I've never done android development so this kind of use is something new to me. 

However I imagine that supporting RegEx would match your need, since it would be possible to match any method in the `console` namespace but `info`, `warn` and `error`, with something similar to: `/console\.(?!info|warn|error)\w+/g`, and wouldn't be too complicated to implement. 
Anyway... I'm just throwing ideas here, feel free to adapt as you see fit. :smile: 

I'll wait for your pull request ;)

Thanks

**Comment by atian25** [comment]
got some problem when using `groundskeeper` with `grunt-contrib-uglify`, 
and found that  I can do this just using `uglify`: 

```
uglify: {
      options: {
        mangle: {
          except: ['require','exports', 'module', 'window']
        },
        compress: {
          pure_funcs: [
            "console.log",
            //"console.info",
            //"console.warn",
            //"console.error",
            "console.assert",
            "console.count",
            "console.clear",
            "console.group",
            "console.groupEnd",
            "console.groupCollapsed",
            "console.trace",
            "console.debug",
            "console.dir",
            "console.dirxml",
            "console.profile",
            "console.profileEnd",
            "console.time",
            "console.timeEnd",
            "console.timeStamp",
            "console.table",
            "console.exception"
          ]
        }
   }
}
```

**Comment by couto** [comment]
When I started [groundskeeper](https://github.com/Couto/groundskeeper) two years ago, [Uglify2](https://github.com/mishoo/UglifyJS2) (the tool behind grunt-contrib-uglify) was a few months old, it was in its beginnings and it was barely usable at that time...

By now, Uglify2 does pretty much everything that groundskeeper does, in one way or another. 
It's an awesome tool, I also use it every day.
